Add votes
xbulat/qna pull request #8
Opened 2019-04-23 05:35 UTC by xbulat

2019-04-23 09:03 UTC, vkurennov requested changes

2019-04-23 09:03 UTC, vkurennov commented on app/controllers/concerns/votes.rb
> +    unless current_user.author_of?(@voted)
нужно вовзращать ответ и если условие не выполнилось, здесь подойдет 403 статус (`head :forbidden`), потому что иначе, рельсы будут пытаться отрендерить вид like, которого нет, что приведет к 500й ошибке

2019-04-23 09:03 UTC, vkurennov commented on app/models/concerns/rating_score.rb
> +module RatingScore
Очень сложная архитектура, достаточно сделать поле с рейтингом или вообще считать его "на лету", а лишняя модель  только все усложняет и не дает профита.

2019-04-23 09:03 UTC, vkurennov commented on app/models/concerns/rating_score.rb
> +    self.rating = Rating.new if self.rating.nil?
несмотря на то, что модель рейтинга не нужна, на будущее: такие вещи записываются через `||=`

2019-04-23 09:03 UTC, vkurennov commented on app/models/concerns/rating_score.rb
> +      rating.votes.create!(user: user, like: true )
опять же, все упрощается, если у голоса значение сделать числовым (+/- 1), тогда общий рейтинг считается за один запрос к базе и не надо его поддерживать в актуальном состоянии.

2019-04-23 09:03 UTC, vkurennov commented on app/models/concerns/rating_score.rb
> +      rating.increment(:score).save!
в таких вещах всегда есть вероятность race condition. что, если два юзера одновременно будут обновлять рейтинг? Они загрузят текущий рейтинг (пусть он будет 0 в этот момент), каждый из них увеличит его на 1, но т.к. оба начали с нуля, рейтинг будет 1, а не 2, как должен быть. Этого мы избегаем, если сами значения голоса храним в модели Vote (тогда просто создается 2 модели) и общий рейтинг считаем из них же.

Да, потенциально, это может иметь проблемы с производительностью, но во-первых, еще не факт, что это случиться (т.е. дожить надо), во-вторых, когда это станет реальной проблемой, тогда и надо будет думать как это решать. "Преждевременная оптимизация - зло", как сказал Кнут.

2019-04-23 09:03 UTC, vkurennov commented on app/models/user.rb
> +    object.rating.votes.find_by(user: self)
у тебя абсолютно перепутана цепочка ассоциаций. ты же в модели юзера, у него есть связь с голосами, вот от нее и пляши: `votes.where(votable: object).first`. проще, не правда ли?

2019-04-23 09:03 UTC, vkurennov commented on app/models/vote.rb
> +class Vote < ApplicationRecord
нужна валидация на допустимые значения голоса

2019-04-27 08:38 UTC, vkurennov approved these changes

2019-04-27 08:38 UTC, vkurennov commented on app/models/concerns/rating_score.rb
> +    ratings.pluck(:score).sum
лучше не так сделать, в вот так: `ratings.sum(:score)`. разница в том, что в твоем варианте, ты сначала из базы все загружаешь в память, в массив и затем по нему делаешь  sum, что медленнее и затратнее по памяти. а в моем варианте посылается запрос к БД на суммирование (агрегатная функция SUM) и база сразу возвращает сумму, что значительно быстрее и память не тратит

2019-04-27 18:32 UTC, xbulat commented on app/models/concerns/rating_score.rb
> +    ratings.pluck(:score).sum
Учитывал это, но делал по памяти, и спутал методы. Спасибо.

2019-04-27 18:32 UTC, merged